// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCV3Q3Z7_oif622izH7MmPv7ubn8J08vxg',
    appId: '1:844040717057:android:8d7c0d53d1a8c8a3611100',
    messagingSenderId: '844040717057',
    projectId: 'metham-d8945',
    storageBucket: 'metham-d8945.appspot.com',
  );
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCV3Q3Z7_oif622izH7MmPv7ubn8J08vxg',
    appId: '1:844040717057:android:8d7c0d53d1a8c8a3611100',
    messagingSenderId: '844040717057',
    projectId: 'metham-d8945',
    storageBucket: 'metham-d8945.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBz-pBztgRl2dwmUCSP-wg4d61ZsFbeHfs',
    appId: '1:844040717057:ios:43bb5f46f98719eb611100',
    messagingSenderId: '844040717057',
    projectId: 'metham-d8945',
    storageBucket: 'metham-d8945.appspot.com',
    iosClientId:
        '844040717057-6qinn07puknophn413uau9q1brl12dto.apps.googleusercontent.com',
    iosBundleId: 'com.midas.metham',
  );
}
